POST http://localhost:63342/drawio-dev/src/main/webapp/drawio/saveFile
Accept: */*
Accept-Language: zh-CN,zh;q=0.9
Connection: keep-alive
Content-Type: application/json

{"filename":"未命名绘图.drawio","fileId":1748095293539,"data":"<mxfile host=\"localhost\" agent=\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36\" version=\"@DRAWIO-VERSION@\">\n  <diagram name=\"第 1 页\" id=\"_yR_bq-eNWFAo7aO-hAn\">\n    <mxGraphModel dx=\"1434\" dy=\"113\" grid=\"1\" gridSize=\"10\" guides=\"1\" tooltips=\"1\" connect=\"1\" arrows=\"1\" fold=\"1\" page=\"1\" pageScale=\"1\" pageWidth=\"827\" pageHeight=\"1169\" math=\"0\" shadow=\"0\">\n      <root>\n        <mxCell id=\"0\" />\n        <mxCell id=\"1\" parent=\"0\" />\n        <mxCell id=\"GUU_w2BMdDwS_WW3My_n-1\" value=\"\" style=\"rounded=0;whiteSpace=wrap;html=1;\" parent=\"1\" vertex=\"1\">\n          <mxGeometry x=\"70\" y=\"40\" width=\"120\" height=\"60\" as=\"geometry\" />\n        </mxCell>\n      </root>\n    </mxGraphModel>\n  </diagram>\n</mxfile>\n"}

###

###